### ISSUE TITLE
Please Consider Using BRRP (so texture will follow any texturepack)

### ISSUE THREAD

**Issue by ardissaps** [HexBugOrion/UnEarthed#101]
Would you like to support BRRP for texture? Like if we change texture pack the Unearthed will change accordingly :

Currently Diorite does not change texture when using texture pack :
![image](https://user-images.githubusercontent.com/82106625/174442903-24ee7ea4-ba55-4872-95e1-769f518200f0.png)

https://www.curseforge.com/minecraft/mc-mods/better-runtime-resource-pack

**Comment by lilypuree** [comment]
Neither ARRP nor BRRP provides support for all modloaders. I will add support once a similar system exists everywhere.
