### ISSUE TITLE
Need Slab Block for Uneearthed block.

### ISSUE THREAD

**Issue by ardissaps** [HexBugOrion/UnEarthed#102]
This mod is great. Thanks you for making one!
Would you like to add slab?

**Comment by lilypuree** [comment]
What slab are you asking for?

**Comment by ardissaps** [comment]
> What slab are you asking for?

Every block added by unearthed?
![uneartedslab](https://user-images.githubusercontent.com/82106625/175506942-da3dd7f0-8689-433d-9308-74118f716b29.jpg)
This is Terralith (Forested Highland Biome) generation with Unearthed that could change the stone slab to Unearthed version.

**Comment by lilypuree** [comment]
So  are you asking to replace slabs when generating? Or do you want slabs for every block type?

**Comment by ardissaps** [comment]
> So are you asking to replace slabs when generating? Or do you want slabs for every block type?

Actually priority for the one generated, for consistency with Terralith slab generation. But even better if all have slab, as like vanilla stone have slab. But no hurry, your mod is already good as is, just need few addition.

**Comment by lilypuree** [comment]
not all vanilla blocks have slabs, blocks that don't have slabs in Unearthed are intentional.

**Comment by Answordy** [comment]
I would like to suggest the same thing. But in a way less confusing way.

Basically it would be nice to replace stone, andesite, diorite and granite slabs too in world generation to their Unearthed counterparts like the mod does with full blocks already. For the simple reason to have an even better compatibility with Terralith and maybe other world gen mobs that use slabs in generation. Like on the following picture. Stone is replaced with mudstone, but stone slabs are not.
![2022-06-26_19 45 40](https://user-images.githubusercontent.com/82783515/175827722-fb29a422-8cbe-48eb-ba43-0b3e340ee98d.jpg)

**Comment by ardissaps** [comment]
But the more I look at them, it actually does not look that bad. Lets say it is just some piece of rock laying one another rock, which is in real life sometimes happen (like because natural disaster like wind tsunami or volcanic disaster).

**Comment by Answordy** [comment]
Depends on the environment I think. On my picture they might look like that, but most of the time they don't do. There are better alternatives to that type of thing, a lot of mods add rocks, pebbles and such. I would still like to see them being replaced, I think that would be a great additon to immersion and compatibility. But you can close this issue if you don't agree since we have #98 already.

**Comment by lilypuree** [comment]
Terralith compability is planned
