### ISSUE TITLE
Vanilla Grass Block generate on top of Conglomerate instead of Conglomerate Grassy Regolith

### ISSUE THREAD

**Issue by ardissaps** [HexBugOrion/UnEarthed#104]
Is it a bug or supposed to be?
![image](https://user-images.githubusercontent.com/82106625/177042234-134377b0-be6a-44e2-b086-5e1ed331f346.png)
Plain Biome (1.18.2)

**Comment by lilypuree** [comment]
This is intended. Plains biomes are covered by dirt regardless of the underlying stone type. This can be configured via datapacks.
