### ISSUE TITLE
It doesn't work with the latest version of forge

### ISSUE THREAD

**Issue by simonjonnemeth** [HexBugOrion/UnEarthed#12]
![2020-10-30](https://user-images.githubusercontent.com/1496797/97746652-9df5e100-1ae2-11eb-825b-ee865493b1b6.png)

**Comment by Rayzilla68** [comment]
Exact same issue. Anything past Forge 34.1.25 gets this error for me. 

[crash-2020-11-03_14.32.03-fml.txt](https://github.com/HexBugOrion/UnEarthed/files/5483900/crash-2020-11-03_14.32.03-fml.txt)

**Comment by kreezxil** [comment]
Same here, Ice&Fire had this problem, the recently did something to fix the issue.


1.0.5 crashes dedicated server Forge 1.16.3 build 34.1.42

Notes:
     ExceptionInInitializerError: null

crash report: 
http://paste.ubuntu.com/p/k4NVNZ5v87/

fml server latest: 
http://paste.ubuntu.com/p/2qChgn267H/

**Comment by CorgiTaco** [comment]
https://www.curseforge.com/minecraft/mc-mods/unearthed-forge/files/3103900
