### ISSUE TITLE
[Suggestion] Make ores drop into their vanilla/base mod variant

### ISSUE THREAD

**Issue by Excederus** [HexBugOrion/UnEarthed#14]
For example any iron ore drops as vanilla iron ore.

This is a thing I was kinda expecting because Underground Biomes Construct does it and it's really convenient because you don't end up with 6 different Iron ores in your inventory.

**Comment by K0-RR** [comment]
No please no. This is stupid.

**Comment by ghost** [comment]
I would like it if the Unearthed ores could be crafted into the default ores. Just adding a 1:1 recipe would be great. That way we could enjoy the aesthetic when we wanted, but we could also stack our loot efficiently when it's convenient.

**Comment by K0-RR** [comment]
You can just take a furnace with you when you go mining.

**Comment by K0-RR** [comment]
About "Unearthed ores could be crafted into the default ores. Just adding a 1:1 recipe would be great." If this could be disabled/enabled in the config then I'm ok with this.

**Comment by CorgiTaco** [comment]
Achievable via datapacks. In latest, they all drop a common "iron_ore" item
