### ISSUE TITLE
Error stating mod designed for older version

### ISSUE THREAD

**Issue by Rayzilla68** [HexBugOrion/UnEarthed#15]
[latest.log](https://github.com/HexBugOrion/UnEarthed/files/5503523/latest.log)

Tested with only Unearthed Version 1.0.6 in the mods folder and within a custom mod pack:

When opening a world, either existing or new, I get a screen stating:

"Errors in currently selected datapacks prevented the world from loading. You can either try to load it with only the vanilla datapack ("safe mode"), or go back to the title screen and fix it manually."

Opening the datapacks screen has Unearthed highlighted in red and saying it is "Incompatible" and "Made for an older version of Minecraft."

No error logs were generated.

**Comment by EgorimM** [comment]
I have the same error.
I've tested 1.16.2, 1.16.3 and 1.16.4.
Did not work.
I know this is stupid, but I've been trying to fake resources since Unearthed 1.0.5. Did not work.
I am very bad at this.

**Comment by BaccarWozat** [comment]
Same error here. This has happened to a lot of 1.16.x mods in my modpack, about half of which are 1.16.4. Forge forums do not explain what is supposed to be done to fix the datapacks. Is it a Forge thing or a 1.16.4 thing?

**Comment by EgorimM** [comment]
Сan you just update the mod to a new version of the forge without adding anything?
Or was this update just adding support for a new version of the forge without adding anything else?

**Comment by aburone** [comment]
Probably related:

Unearthed encountered an error during the load_registries event phase java.lang.ExceptionEnInitializerError: null

unearthed-1.0.4.jar
and
unearthed-1.0.5.jar

Forge version
42

Works on Forge 23

**Comment by EgorimM** [comment]
> Probably related:
> 
> Unearthed encountered an error during the load_registries event phase java.lang.ExceptionEnInitializerError: null
> 
> unearthed-1.0.4.jar
> and
> unearthed-1.0.5.jar
> 
> Forge version
> 42
> 
> Works on Forge 23

I know it.
i know older versions of this mod work with forge 23.

**Comment by CorgiTaco** [comment]
Fixed in latest
