### ISSUE TITLE
Unearthed {Fabric 1.16.3-16.4} Tag Request

### ISSUE THREAD

**Issue by litjohn50** [HexBugOrion/UnEarthed#16]
Is there anyway that you can add C:stones tag to your Rocks that spawn in caves, 

Reason:  Some other mods are having issues breaking your stones since there is no common tag between them. 

Like Unearthed:slate, C:stones, and so on... 

Thanks would be a massive help to modpack development!

**Comment by CorgiTaco** [comment]
I already do my stones in the tag "base_stone_overworld" which is provided by vanilla so that's on them for not using the vanilla tag

**Comment by CorgiTaco** [comment]
If you truly require it, you can create a datapack on your own and do that for yourself

**Comment by CorgiTaco** [comment]
wait wait wait you might have a point whoops

**Comment by kwpugh** [comment]
Ok, I figured out how to check for "base_stone_overworld", so that works.

**Comment by kwpugh** [comment]
In case this comes up again where a dev wants to target the added stones:


`block = worldIn.getBlockState(pos).getBlock();							
			
  if (block.isIn(BlockTags.BASE_STONE_OVERWORLD) || block.isIn(BlockTags.BASE_STONE_NETHER))
 {
      // do something you want to do
 }'

Works fine now.
