### ISSUE TITLE
[Major Bug] Ore variants hardness is higher than vanilla

### ISSUE THREAD

**Issue by Dimerite** [HexBugOrion/UnEarthed#18]
Just started playing with this mod and found that I couldn't mine coal/iron variants with a stone pickaxe. So I gave myself iron with commands and I still can't mine coal/iron neither gold.

I asume problem will happen with all the ores, I suggest checking all of them and balance with vanilla. But just in case, the ids of the ores I have failed to mine with an iron pickaxe in survival:

rhyolite_gold_ore
rhyolite_coal_ore
limestone_coal_ore
conglomerate_gold_ore
lignite_iron_ore

Fabric 1.16.4
UnEarthed 1.0.5

Edit: I have tried with diamond an netherite too, same thing.

**Comment by optionboom** [comment]
I haven't had this issue, although I haven't encountered those specific variants. In fact, I was able to mine an iron ore of some type with a wooden pickaxe, which isn't supposed to be possible. Very weird.

**Comment by CorgiTaco** [comment]
Closing this, if issue persists in latest version, reopen this. https://www.curseforge.com/minecraft/mc-mods/unearthed-fabric/files/3196531
