### ISSUE TITLE
Error during load 1.16.4

### ISSUE THREAD

**Issue by cyberpunkbln** [HexBugOrion/UnEarthed#19]
Hello,

i have an error during load.

[crash-2020-11-13_12.13.40-fml.txt](https://github.com/HexBugOrion/UnEarthed/files/5536434/crash-2020-11-13_12.13.40-fml.txt)

**Comment by Mikaaah** [comment]
Unearthed 1.0.5 Doesn't work with 1.16.4, Atleast the curseforge states 1.16.2/1.16.3 and requires forge 34.1.25 or lower

**Comment by cyberpunkbln** [comment]
Ah okay thx, some mods thats are for 34er Forge work with my modpack, and i was hopefully that this mod work, too.

Is it a special function that Unearthed uses in 34er Forge or is it possible to complile Unearth against 35er Forge?

**Comment by CorgiTaco** [comment]
Should be fixed in latest.
