### ISSUE TITLE
Unearthed 1.0.5 MCV 1.16.2/1.16.3 crashes dedicated server Forge 1.16.3 build 34.1.42

### ISSUE THREAD

**Issue by kreezxil** [HexBugOrion/UnEarthed#20]
Notes:
     failed to load registries

crash report: 
https://gist.github.com/23c487a90707d06d5329af00804ef9af

fml server latest: 
https://gist.github.com/3e0ba238c199a21d84b5d9f55f393c4b

**Comment by CorgiTaco** [comment]
Should be fixed in latest.
