### ISSUE TITLE
[Bug] - [Fabric] incompatibility with wildworld

### ISSUE THREAD

**Issue by SylisMC** [HexBugOrion/UnEarthed#22]
Crash on join world when loading unearthed with wildworld, 
[crash WW+UE.txt](https://github.com/HexBugOrion/UnEarthed/files/5712009/crash.WW%2BUE.txt)

**Comment by SylisMC** [comment]
with the little knowledge i have and some research it looks like wild world might be to blame 
https://bitbucket.org/andre111/wildnature/issues/4/wild-worlds-has-unregistered

**Comment by CorgiTaco** [comment]
Closing this, if issue persists in latest version, reopen this. https://www.curseforge.com/minecraft/mc-mods/unearthed-fabric/files/3196531
