### ISSUE TITLE
Mountains generate a layer of stone on top of unearthed replacements

### ISSUE THREAD

**Issue by FewerFlaws** [HexBugOrion/UnEarthed#25]
Steep sides of mountains look odd with a thin layer of stone on top.  One solution is thickening this layer.  Another is replacing it with unearthed ore just like stone below the surface.

Personally, I would prefer thickening the vanilla stone layer.  This is because vanilla stone has significantly more recipes than variant stones.  Thickening the surface layer would keep vanilla stone plentiful.

![2021-01-17_15 52 39](https://user-images.githubusercontent.com/75643699/104859925-6d516680-58dd-11eb-8b9f-4c39ba34a51f.png)

**Comment by FewerFlaws** [comment]
On the mountain in the screenshot I found a stack of 11 visible marble blocks in a particularly steep spot.  Thickening the surface layer to 15 blocks would likely resolve the issue to satisfaction.

Another possibility is using light from the sky to cancel the replacement stone types.  If this is feasible, thickening the surface layer to 3 blocks and implementing the light solution to address steep surfaces would probably be ideal.

**Comment by CorgiTaco** [comment]
Should be fixed in latest
