### ISSUE TITLE
All ores can't be smelted

### ISSUE THREAD

**Issue by Golden-King05** [HexBugOrion/UnEarthed#26]
I'm just trying out the mod and I really like it but I have a problem that whenever I try to smelt iron at the beginning of the game I am unable to as the furnace does not seem to recognize it. Any clue why this may be happening?

**Comment by Golden-King05** [comment]
I just thought I should clarify the furnace is also fine as it can smelt cobble to stone just fine

**Comment by lilypuree** [comment]
What version of the mod are you using, and with what mods?

**Comment by CorgiTaco** [comment]
Should be fixed in latest.
