### ISSUE TITLE
[Fabric] unearthed:someblock does not exist. Defaulting to stone!

### ISSUE THREAD

**Issue by K0-RR** [HexBugOrion/UnEarthed#28]
unearthed:pumice_cobble does not exist. Defaulting to stone!
unearthed:schist_cobble does not exist. Defaulting to stone!
unearthed:phyllite_cobble does not exist. Defaulting to stone!
unearthed:conglomerate_cobble does not exist. Defaulting to stone!

minecraft:stone_cobble does not exist. Defaulting to stone!

**Comment by FewerFlaws** [comment]
I've also seen these warnings in my log =\

**Comment by CorgiTaco** [comment]
Closing this, if issue persists in latest version, reopen this. https://www.curseforge.com/minecraft/mc-mods/unearthed-fabric/files/3196531
