### ISSUE TITLE
You can't smelt ores

### ISSUE THREAD

**Issue by Lieutenant2014** [HexBugOrion/UnEarthed#3]

**Comment by CorgiTaco** [comment]
What version?

**Comment by Lieutenant2014** [comment]
1.16.2 1.0.1, and i double checked, it seems to just be iron ore you can't smelt

**Comment by CorgiTaco** [comment]
Forge or fabric?

**Comment by Lieutenant2014** [comment]
Fabric

**Comment by CorgiTaco** [comment]
Could you be more specific as to which iron ore? I just tested a few and they work fine

**Comment by Lieutenant2014** [comment]
Hmm, this may be a mod on my end, lemme check some things

**Comment by Lieutenant2014** [comment]
It was gravel ores. How odd

**Comment by CorgiTaco** [comment]
Yeah he replaces the entire tag it seems
