### ISSUE TITLE
Server Crash Caused by Lichen

### ISSUE THREAD

**Issue by IAmSneak** [HexBugOrion/UnEarthed#36]
Server crashed with this crash report. 
Minecraft 1.16.4
V1.1
[crash-2021-02-17_00.00.13-server.txt](https://github.com/CorgiTaco/UnEarthed/files/5993380/crash-2021-02-17_00.00.13-server.txt)

**Comment by NolanJCarr** [comment]
Same thing happening too me

**Comment by NolanJCarr** [comment]
My server is currently unplayable until this gets fixed; how long do you think this will take? If it will be a long time, is there any alternative I could do temporarily to fix it?

**Comment by lilypuree** [comment]
fixed
