### ISSUE TITLE
Lichen replaces blocks in the ground

### ISSUE THREAD

**Issue by saltyseadoggo** [HexBugOrion/UnEarthed#38]
I've noticed several areas in our new survival world where there are holes in the ground that didn't used to be there, and are filled with lichen, and surrounded by lichen and near water. I'm assuming that it's spreading improperly and replacing blocks in the ground.

![2021-02-16_19 05 03](https://user-images.githubusercontent.com/69029346/108168485-40df6480-70ac-11eb-8b3c-ec970ddf6a0a.png)
![2021-02-16_21 10 50](https://user-images.githubusercontent.com/69029346/108168492-4177fb00-70ac-11eb-8d7b-09b173e8ea86.png)
![2021-02-16_21 16 51](https://user-images.githubusercontent.com/69029346/108168494-42109180-70ac-11eb-8a89-92b5b84005fe.png)
![2021-02-16_21 17 04](https://user-images.githubusercontent.com/69029346/108168497-42a92800-70ac-11eb-9fcf-ab70c94ab15c.png)
![2021-02-16_22 02 26](https://user-images.githubusercontent.com/69029346/108168500-4341be80-70ac-11eb-817a-10332742d57c.png)
![2021-02-16_22 54 32](https://user-images.githubusercontent.com/69029346/108168503-43da5500-70ac-11eb-88d3-853a18e9b128.png)

**Comment by Frld4y** [comment]
I've also had this issue, It's been destroying blocks in builds around puddles

**Comment by CmdrJane** [comment]
same issue happens to me too

**Comment by PeculiarOrange** [comment]
This is becoming a serious issue, as if you build near lakes the lichen creeps up to buildings and is now deleting our storage blocks with the items inside.

**Comment by lilypuree** [comment]
Are the puddles intentionally placed?

**Comment by saltyseadoggo** [comment]
I'm not quite sure what you mean by *intentionally?* We don't intend to create them in that they just pop up on their own whenever we or various mobs are in water underground or near shorelines. All of the pictures above are of these instances, although the water in one of the underground ones was cut off by player block placement.

**Comment by lilypuree** [comment]
The lichen replacing blocks have been fixed, but the puddle blocks should spawn only when you jump really hard into a pool of water, not always when you're near water...

**Comment by moeux** [comment]
> The lichen replacing blocks have been fixed, but the puddle blocks should spawn only when you jump really hard into a pool of water, not always when you're near water...

It hasn't.
We are using unearthed-1.1.0 and blocks are still being replace by spawning lichen and it's getting really annoying.
I hope this gets fixed as soon as possible. Lichen really revert all the work you've done regarding building houses etc. And if that's not enough they also can replace blocks which are very hard to come by.

**Comment by lilypuree** [comment]
The latest version is 1.1.1

Edit: are you on Fabric?

**Comment by moeux** [comment]
> The latest version is 1.1.1
> 
> Edit: are you on Fabric?

I'm using Fabric, yes.

**Comment by lilypuree** [comment]
fixed
