### ISSUE TITLE
More configuration options and Lichen replacing blocks

### ISSUE THREAD

**Issue by moeux** [HexBugOrion/UnEarthed#43]
It would be great to have more configuration options, regarding the existence of puddles and liches and/or the frequency of each.
Lichen are a serious issues since they replace existing blocks.
That's the amount of damage they can cause:
![2021-02-24_00 24 01](https://user-images.githubusercontent.com/68925026/108921559-cd52cf80-7636-11eb-89d2-73471c61c80e.png)
All those holes are caused by lichen exclusively.

I'm using Fabric and unearthed-1.1.0, the latest version listed on CurseForge as of the 24th of February.

**Comment by lilypuree** [comment]
Now there is a gamerule for puddle creation, I think that is enough but if you want more just reopen the issue
