### ISSUE TITLE
Top of coal ore is not coal?

### ISSUE THREAD

**Issue by AzureMonument** [HexBugOrion/UnEarthed#46]
So I've only recently (in the last 10 minutes) downloaded this mod and started playing it after adding it to my modpack. I loaded up a new survival world, and went to mine coal. Then, I noticed this?

![2021-02-23_17 04 03](https://user-images.githubusercontent.com/43318292/108880036-deb4c100-75cf-11eb-931c-a4efc863b6f7.png)

The bottom and other sides are normal. I'm... pretty sure this isn't supposed to happen. I'm also pretty sure it may be a compat issue- as I haven't see anyone post an issue on this. I'm still putting this here to see if you have any clue as to what is causing it.

I'm currently running MC 1.16.5, forge v. 36.0.40, and unearthed 1.1.1

**Comment by AzureMonument** [comment]
![2021-02-23_17 15 18](https://user-images.githubusercontent.com/43318292/108880959-cf824300-75d0-11eb-8f5e-d1a32ec7f387.png)
Just found iron, and it seems to apply here as well. (I do have optifine, if that would effect it)

**Comment by lilypuree** [comment]
This is intended

**Comment by K0-RR** [comment]
Why is this intended? Why not make it like in vanilla?
