### ISSUE TITLE
[Crash/Loading Failed] "Mod Loading Failed" Screen says there was an error in the load_registries phase.

### ISSUE THREAD

**Issue by Corvus20** [HexBugOrion/UnEarthed#48]
Using latest available builds of forge 1.16.5 and unearthed on GDLauncher. Architect's Palettes' issues have already been reported to its devs, too. 

![image](https://user-images.githubusercontent.com/75586106/109026530-d8851a00-768d-11eb-9fe7-ecb14baa37ae.png)

[crash-2021-02-24_10.40.27-fml.txt](https://github.com/CorgiTaco/UnEarthed/files/6037174/crash-2021-02-24_10.40.27-fml.txt)

**Comment by lilypuree** [comment]
I hope it's fixed in the latest version
