### ISSUE TITLE
Lichen has a solid collision box

### ISSUE THREAD

**Issue by saltyseadoggo** [HexBugOrion/UnEarthed#50]
Lichen has a solid collision box. You can see this by walking over a lichen block with the F3 menu open and watching the Y level change, by walking along a wall up to a lichen block, which will stop you, and, as I discovered it, by trying to climb a scaffolding tower to the top when lichen is on top of it, which prevents you from climbing it all the way.

**Comment by K0-RR** [comment]
https://github.com/CorgiTaco/UnEarthed/issues/33

**Comment by saltyseadoggo** [comment]
Groovy. I'll make this issue just about the lichen then, I guess.
