### ISSUE TITLE
Iron ore variants don't respect Fortune enchantment

### ISSUE THREAD

**Issue by saltyseadoggo** [HexBugOrion/UnEarthed#51]
The Fortune enchantment cannot be used to increase the yield of iron ore items from the variant iron ores. This is a pretty common feature in other mods which make iron and gold ores drop items instead of themselves, and is useful to make mining more viable in the face of iron and gold farms.

Steps to Reproduce:
- Start Minecraft with only UnEarthed and the Fabric API loaded.
- Create a new world in Creative mode.
- Lay out some UnEarthed iron ores.
- Obtain any pickaxe capable of mining iron ore.
- Run `/enchant @p fortune 3` to enchant the pickaxe with Fortune III.
- Go into survival mode, and break the ores. Note that you always receive only one ore item per ore, in spite of the enchantment.

**Comment by K0-RR** [comment]
This is not a bug. It's vanilla behaviour.

**Comment by saltyseadoggo** [comment]
Mm, not quite. Vanilla behaviour would be the iron ore variants dropping their block forms; UnEarthed instead makes them all drop an iron ore *item* that is not a block. The other element of vanilla behaviour is that ores which drop items and not blocks drop more items when mined with Fortune. The devs can deem being able to gather more iron than usual from each ore overpowered or not, but that's their call.

**Comment by saltyseadoggo** [comment]
Mods which make iron and gold ores drop items and not blocks are somewhat common, and a common thread is for them to use this as an opportunity to let Fortune work on them. I simply thought I would suggest this.

**Comment by K0-RR** [comment]
Oh so you mean iron ingot.
Wait so Unearthed iron ores drop iron ingots instead of itself?

**Comment by saltyseadoggo** [comment]
Nah, they have a little brown 'Iron Ore' item that cooks into the ingot, that's separate from all of the iron ore blocks.

![2021-03-03_15 45 37](https://user-images.githubusercontent.com/69029346/109887946-874dcb00-7c37-11eb-93c3-62f2eee22cb6.png)

**Comment by lilypuree** [comment]
I would not make them be affected by fortune enchantments
