### ISSUE TITLE
Lichens delete blocks

### ISSUE THREAD

**Issue by MopsTMC** [HexBugOrion/UnEarthed#59]
I have noticed that when lichens spread they have the tendency to replace blocks around them. I have had occurrences of lichens replacing obsidian over lava in caves, grass blocks and mineshaft blocks,  which after a long time results in holes everywhere.

https://user-images.githubusercontent.com/74558936/111959919-c4e79a80-8af7-11eb-8265-ef20f9dd2874.mp4

The platform above in the video has waterlogged lichens. It also seems like this is more common with flowing water but I have seen deleted blocks even on lakes. I can attach more screenshots if needed.

**Comment by VasilisMylonas** [comment]
I can confirm.

**Comment by MopsTMC** [comment]
Had an outdated version of the mod and didn't notice the recent update
