### ISSUE TITLE
disable puddles command not working for fabric

### ISSUE THREAD

**Issue by EndarianDrodagin** [HexBugOrion/UnEarthed#63]
i was playing in a world with a friend and seen that the moss was eating our base including things like the altar from bewitchment. when i tried to find a fix i seen that the command was an option but when i tried to input it the command was invalid saying that gamerule dose not exist. do not know if this is also a problem with the forge version but i know it is not working in fabric.

**Comment by lilypuree** [comment]
The fabric version has not been updated yet.
