### ISSUE TITLE
Weird random client-side? lichen generation

### ISSUE THREAD

**Issue by JumperREDACTED** [HexBugOrion/UnEarthed#66]
Playing on a server, sometimes random lichen appears. Updating the block fixes it or right clicking it fixes it. When destroyed, they drop the block that is supposed to be there. Sometimes it's waterlogged, sometimes it's not. They don't appear only on world generation either, but just randomly. Sometimes they are invisible, and right clicking them makes a whole group appear, (But if they are waterlogged, even the invisible ones slow you down.) Restarting the server fixes it temporarily, relogging doesn't. Seems to always appear on the same y level but not completely sure. They also usually appear in the same places repeatedly, linked into a line. I assume it's a conflict of some world gen mods since the server has a bunch, 

![2021-06-15_18 18 50](https://user-images.githubusercontent.com/83337894/122089106-ba8f2100-ce06-11eb-9da1-70f197c6abb9.png)
![2021-06-15_18 19 44](https://user-images.githubusercontent.com/83337894/122108749-dac9da80-ce1c-11eb-9c2d-a6d6452cc6d8.png)
![2021-06-10_11 44 33](https://user-images.githubusercontent.com/83337894/122089340-f4f8be00-ce06-11eb-9805-4107fdd8d374.png)

Client log from when none appeared yet:
[latest.txt](https://github.com/CorgiTaco/UnEarthed/files/6657297/latest.txt)
Server log from same
[latest.txt](https://github.com/CorgiTaco/UnEarthed/files/6657335/latest.txt)

Client log from when they were there:
[2021-06-15-3.txt](https://github.com/CorgiTaco/UnEarthed/files/6657349/2021-06-15-3.txt)
Server:
[2021-06-15-2.txt](https://github.com/CorgiTaco/UnEarthed/files/6657373/2021-06-15-2.txt)

**Comment by lilypuree** [comment]
woah this is really weird lol

**Comment by lilypuree** [comment]
Does the lichen still destroy blocks?

**Comment by JumperREDACTED** [comment]
> Does the lichen still destroy blocks?

not sure what you mean exactly? the actual blocks are still there, just weirdly hidden. they appear correctly if you right click the lichen or restart server (and they drop their correct material if you break the lichen)

**Comment by JumperREDACTED** [comment]
![image](https://user-images.githubusercontent.com/83337894/124806677-40f9d700-df5d-11eb-8691-d54488e2ad20.png)
happens in singleplayer too, apparently
