### ISSUE TITLE
Server crashes when lichen attempts to convert a block to a regolith

### ISSUE THREAD

**Issue by Desktop-Hero** [HexBugOrion/UnEarthed#70]
Our server keeps crashing repeatedly every few hours. I believe the issue is with lichen conversion, because of the crash reports. Here is the entire crash report.

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 7/21/21 12:57 AM
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at net.lilycorgitaco.unearthed.block.LichenBlock.tryErodeBlock(LichenBlock.java:141)
	at net.lilycorgitaco.unearthed.block.LichenBlock.method_9514(LichenBlock.java:95)
	at net.minecraft.class_4970$class_4971.method_26199(class_4970.java:878)
	at net.minecraft.class_3218.redirect$zfm000$redirectBlockStateTick(class_3218.java:2083)
	at net.minecraft.class_3218.method_18203(class_3218.java:522)
	at net.minecraft.class_3215.method_20801(class_3215.java:390)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at net.minecraft.class_3215.method_14161(class_3215.java:368)
	at net.minecraft.class_3215.method_12127(class_3215.java:337)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.class_3176.method_3813(class_3176.java:312)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.lilycorgitaco.unearthed.block.LichenBlock.tryErodeBlock(LichenBlock.java:141)
	at net.lilycorgitaco.unearthed.block.LichenBlock.method_9514(LichenBlock.java:95)
	at net.minecraft.class_4970$class_4971.method_26199(class_4970.java:878)
	at net.minecraft.class_3218.redirect$zfm000$redirectBlockStateTick(class_3218.java:2083)
	at net.minecraft.class_3218.method_18203(class_3218.java:522)
	at net.minecraft.class_3215.method_20801(class_3215.java:390)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at net.minecraft.class_3215.method_14161(class_3215.java:368)
	at net.minecraft.class_3215.method_12127(class_3215.java:337)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)

-- Affected level --
Details:
	All players: 2 total; [class_3222['Sgt_Falchion'/526, l='ServerWorld minecraft:overworld world3', x=-113.62, y=89.74, z=-1454.59], class_3222['UAGpog'/2920, l='ServerWorld minecraft:overworld world3', x=-364.30, y=63.00, z=-3051.84]]
	Chunk stats: ServerChunkCache: 5178
	Level dimension: minecraft:overworld
	Level spawn location: World: (-479,94,-1355), Chunk: (at 1,5,5 in -30,-85; contains blocks -480,0,-1360 to -465,255,-1345), Region: (-1,-3; contains chunks -32,-96 to -1,-65, blocks -512,0,-1536 to -1,255,-1025)
	Level time: 3836498 game time, 3927340 day time
	Level name: world3
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 83181 (now: false), thunder time: 70518 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.class_3176.method_3813(class_3176.java:312)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 4.4.232-1.el7.elrepo.x86_64
	Java Version: 1.8.0_292, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), AdoptOpenJDK
	Memory: 511031288 bytes (487 MB) / 3363307520 bytes (3207 MB) up to 7456948224 bytes (7111 MB)
	CPUs: 4
	JVM Flags: 2 total; -Xmx8000M -Xms128M
	Fabric Mods: 
		added_origins_mod: Added Origins V2.0.0
		additionalbars: Additional Bars 2.0.4
		advanced_runtime_resource_pack: Runtime Resource Pack 0.3.11
		amecsapi: Amecs API 1.1.4+mc1.16.5
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		appletreesrev: Apple Trees Revived 1.3
		artifacts: Artifacts 3.2.1+fabric
		autoconfig1u: Auto Config v1 Updated 3.3.1
		bedspreads: Bedspreads 1.3.1-1.16.4
		bettercaves: YUNG's Better Caves 1.16.5-1.2
		bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0.2
		betterstrongholds: YUNG's Better Strongholds 1.16.5-1.0
		bitsandchisels: BitsAndChisels 2.3.2
		bno: Basic Nether Ores 1.16.5-5.5.0-Fabric
		bowinfinityfix: Bow Infinity Fix rv9
		byg: BYG 1.1.8
		caelus: Caelus API 0.0.15-1.16.4
		cakechomps: Cake Chomps 1.3.0-1.16.4
		candlebackport: Candle Backport 1.0
		cardinal-components-base: Cardinal Components API (base) 2.8.2
		cardinal-components-block: Cardinal Components API (blocks) 2.7.9
		cardinal-components-entity: Cardinal Components API (entities) 2.8.2
		cardinal-components-item: Cardinal Components API (items) 2.8.2
		classicalart: Classical Art 1.0.0
		cleanview: CleanView 1.16.5-v1-fabric
		cloth-api: Cloth API 1.4.9
		cloth-armor-api-v1: Cloth Armor API v1 1.4.9
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-common-events-v1: Cloth Common Events v1 1.4.9
		cloth-config2: Cloth Config v4 4.11.26
		cloth-datagen-api-v1: Cloth Datagen v1 1.4.9
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.4.9
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.9
		cloth-utils-v1: Cloth Utils v1 1.4.9
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		comforts: Comforts 0.0.3-1.16.5
		compostable-rottenflesh: Compostable Rotten Flesh 1.0.0
		controlling: Controlling For Fabric 1.1.2
		cookiecore: Oreo Core 0.0.4
		cosmetic-armor: Cosmetic Armor 1.0.0
		couplings: Couplings 1.3.3
		craftable_enchanted_golden_apple: Craftable Enchanted Golden Apple 1.0.0
		craftnstar: Craftable nether star 1.1.0
		crawl: Crawl 0.8.4
		croptopia: Croptopia 1.4.0
		curioofundying: Curio of Undying 1.1.1-1.16.5
		curios: Curios API 0.0.13-1.16.5
		curiouselytra: Curious Elytra 1.1.1-1.16.5
		customizableelytra-fabric: Customizableelytra Fabric 1.3.1
		editsign: Edit Sign 2.2.0
		emotecraft: Emotecraft 2.0.6
		enhanced_mushrooms: Enhanced Mushrooms 1.0.2
		enhancedcelestials: Enhanced Celestials 1.0.2
		enva: Environmental Armor 1.3.1
		extraorigins: Extra Origins 1.16.5-12
		fabric: Fabric API 0.36.0+1.16
		fabric-api-base: Fabric API Base 0.3.0+c88702897d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+6aebe11a7d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.10+3661eaa17d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+61336ba97d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+c88702897d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.3+f941baf07d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-language-kotlin: Fabric Language Kotlin 1.6.1+kotlin.1.5.10
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.3+e3c9d0627d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+c88702897d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.11+ca0ef93d7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+8183d3957d
		fabricloader: Fabric Loader 0.11.3
		fallflyinglib: FallFlyingLib 1.1.0
		fantasycraft: Fantasycraft 1.1.3
		fatxporbs: Fat Experience Orbs 0.0.9
		fiber: fiber 0.23.0-2
		frozenup: Frozen-Up-Fabric 1.16.5-1.0.0
		geckolib3: Geckolib 3.0.40
		givemehats: Give Me Hats! 1.5.1
		gravel-ores: Gravel Ores 1.2.0+1.16.2
		imm_ptl_core: Immersive Portals Core 0.99
		improved-stations: Improved Stations 2.0.3
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 8
		kiln: Kiln 1.1.1+1.16.5
		latoorigins: Lato Origins 0.7.3
		lavasponge: Lava Sponge 1.0.1
		libgui: LibGui 3.3.5+1.16.5
		libstructure: Libstructure 1.3
		lithium: Lithium 0.6.6
		maybe-data: Maybe data 1.0.0-1.16.2
		minecraft: Minecraft 1.16.5
		mm: Manningham Mills 2.2
		moborigins: Mob Origins 1.4.0
		more_gems: More Gems 1.1.22
		moremessages: MoreMessages 1.3.0
		morevillagers-fabric: MoreVillagersFabric 1.4.1-SNAPSHOT
		mostructures: Mo' Structures 1.2.0-1.16.5
		mousewheelie: Mouse Wheelie 1.7.3+mc1.16.5
		musica: Musica 1.3.2
		net_openhft_zero-allocation-hashing: zero-allocation-hashing 0.11
		netherite_nugget: Netherite Nugget 1.2.1
		nha: Netherite Horse Armor 1.1.1
		omega-config: OmegaConfig 1.0.4
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.0
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.1
		origins: Origins 0.7.3
		origins-classes: Origins: Classes 1.1.0
		originsplus: Origins Plus 0.0.2
		pehkui: Pehkui 2.2.1+1.14.4-1.17
		pigsteel: Pigsteel Mod 1.5.0
		playerabilitylib: Pal 1.2.1
		polymorph: Polymorph 0.0.10-1.16.5
		portalgun: Portal Gun 1.2.5
		rayon: Rayon 1.2.3
		rayon-core: Rayon Core API 1.2.3
		rayon-entity: Rayon Entity API 1.2.3
		rayon-particle: Rayon Particle API 1.2.3
		reach-entity-attributes: Reach Entity Attributes 1.1.1
		repurposed_structures: Repurposed Structures 1.16.5-1.11.6-fabric
		rightclickharvest: RightClickHarvest 1.0.0
		roughlyenoughitems: Roughly Enough Items 5.12.248
		roughlyenoughitems-api: REI (API) 5.12.248
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.12.248
		roughlyenoughitems-runtime: REI (Runtime) 5.12.248
		simple_backpack: SimpleBackpack 1.0.38
		sit: Sit 1.16.5-11
		skinnedlanterns: Skinned Lanterns 1.16.5-1.1.3
		smoothboot: Smooth Boot 1.16.5-1.6.0
		somnus: Somnus API 0.0.11-1.16.5
		stacc: Stacc 1.0.1
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stoneholm: Stoneholm 1.2.1
		things: Things 0.1.3
		throwabletorch: ThrowableTorch 1.1
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.6
		toomanyorigins: TooManyOrigins 0.1.3
		transporter: Transporter 1.0.3
		trinkets: Trinkets 2.6.7
		tweed: Tweed 3.0.0-beta.26
		unearthed: Unearthed 1.1.0
		unlimiteddragoneggs: Unlimited Dragon Eggs 1.1.1
		untitledduckmod: Untitled Duck Mod 0.2.2
		villagernames: Villager Names 1.6.0
		voicechat: Simple Voice Chat 1.16.5-1.6.4
		voyager: Voyager 1.0.0
		waystones: Waystones 2.0.1
		wiicustomorigins: WiiDude's Custom Origins Mod 1.16.5-13
		wolveswitharmor: Wolves With Armor 1.5.4-1.16.5
		wthit: wthit 2.10.4
		xaerominimap: Xaero's Minimap 21.12.5
		xlpackets: XLPackets 1.1
		yungsapi: YUNG's API 1.16.5-Fabric-5
		zoob: Monster Of The Ocean Depths 3.0.0
	Player Count: 2 / 100; [class_3222['Sgt_Falchion'/526, l='ServerWorld minecraft:overworld world3', x=-113.62, y=89.74, z=-1454.59], class_3222['UAGpog'/2920, l='ServerWorld minecraft:overworld world3', x=-364.30, y=63.00, z=-3051.84]]
	Data Packs: vanilla, Fabric Mods
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by lilypuree** [comment]
Lichen no longer does this on Forge
Fabric 1.16.5 is no longer supported
