### ISSUE TITLE
Grassy Regolith Harvest Tool

### ISSUE THREAD

**Issue by Dark-Arcana** [HexBugOrion/UnEarthed#75]
Mod version: 1.2.1

Unlike normal regolith, the grassy variant does not have a specified harvest tool. This makes it break slower with no available method of increasing dig speed (e.g. Efficiency enchant, better shovel, etc.). These blocks should have the same harvest tool and level as regular grass blocks.

Here is a screenshot to illustrate what The One Probe says when you look at a Beige Limestone Regolith block:

https://cdn.discordapp.com/attachments/874474961086087209/879535128777482250/gg.png

**Comment by lilypuree** [comment]
Fixed in Forge
Fabric 1.16.5 is no longer supported
