### ISSUE TITLE
Server Crash 1.18.1

### ISSUE THREAD

**Issue by Tyrius1** [HexBugOrion/UnEarthed#78]
Exploring on the server in creative and server crashed
https://pastebin.com/jNVdbUfF
Unearthed-forge-1.18.1-2.0.1
Forge 39.0.59

**Comment by Toma400** [comment]
Same here. Happens crossing specific chunk, previously I had no issues.
[crash-2022-02-08_18.46.53-server.txt](https://github.com/lilypuree/UnEarthed/files/8026264/crash-2022-02-08_18.46.53-server.txt)
[2022-02-08-4.log.gz](https://github.com/lilypuree/UnEarthed/files/8026265/2022-02-08-4.log.gz)
[latest.log](https://github.com/lilypuree/UnEarthed/files/8026266/latest.log)
I also use Terralith, TerraBlender and Repurposed Structures, if this makes any difference. Forge 1.18.1, Unearthed 2.0.1.

Also, I just wanted to say that I absolutely love how 1.18 looks with Unearthed. Makes Terralith gen so much more beautiful.

**Comment by TheButterbrotMan** [comment]
Experiencing the same on fabric

**Comment by lilypuree** [comment]
Fixed by the new version, but mind that the update will delete granite/andesite/diorite ore blocks on fabric (not on forge)

**Comment by Toma400** [comment]
Oh, F for Fabric users then. Fortunately I had the issue on Forge.
