### ISSUE TITLE
Stone generates directly under plants and trees

### ISSUE THREAD

**Issue by ghost** [HexBugOrion/UnEarthed#81]
I believe this is because Unearthed does its world generation after everything else. Same bug also makes mods like [Excavated Variants](https://www.curseforge.com/minecraft/mc-mods/excavated-variants) not work.

Grass and a tree growing on rhyolite:
![kuva](https://user-images.githubusercontent.com/98822450/153937670-9ab5bade-826e-4663-8080-cd85c727ef9d.png)

**Comment by lilypuree** [comment]
This is not a bug, it is intended behavior
