### ISSUE TITLE
Granite, Diorite and Andesite not generating

### ISSUE THREAD

**Issue by defenestrationdude** [HexBugOrion/UnEarthed#9]
I noticed that the vanilla decorative stones didn't seem to generate when I created a world, or at least not nearly as commonly as normal, while someone running all the same mods as me except Unearthed did have them spawn. This is only an issue with vanilla stones; other mods that add different stone types such as Vanilla Enhanced and Backrooms do still generate them with Unearthed as they normally would.

**Comment by CorgiTaco** [comment]
Add it to the config
