### ISSUE TITLE
[SUGGESTION] Remove trees/plants/grass from stones

### ISSUE THREAD

**Issue by cowsha** [HexBugOrion/UnEarthed#92]
![изображение](https://user-images.githubusercontent.com/35926994/163665742-92dd8fed-d45d-46c8-90c4-ef22a6d0ee6e.png)

**Comment by lilypuree** [comment]
Intended behavior, could be controlled by changing the region files

**Comment by cowsha** [comment]
how exactly can i do that?

**Comment by lilypuree** [comment]
it is documented on the wiki (except that things have changed and it's now documentation for hyle)

**Comment by cowsha** [comment]
I see nothing on Hyle github wiki page.
Please, give direct link if possible.

**Comment by lilypuree** [comment]
https://github.com/lilypuree/UnEarthed/wiki
