### ISSUE TITLE
Worldgen bugs & other issues

### ISSUE THREAD

**Issue by Reshy** [HexBugOrion/UnEarthed#93]
During World Generation, Schist and Dacite sometimes replace grass/dirt blocks, resulting in generation like the following.
![2022-04-21_01 37 42](https://user-images.githubusercontent.com/2096384/164416796-95973908-5b25-4dbe-b303-1331b5cfc106.png)
![2022-04-21_01 30 35](https://user-images.githubusercontent.com/2096384/164416802-2f046b16-c5ef-4cf8-b872-808883d29c3c.png)
![2022-04-21_01 28 50](https://user-images.githubusercontent.com/2096384/164416826-45603724-239a-4a73-ae82-d3491fa386da.png)

Grassy Regoliths don't properly have their grass model setup for snowy terrain.
![2022-04-20_03 36 49](https://user-images.githubusercontent.com/2096384/164417090-66d1fe28-a4b4-4eb8-92e9-62b55537c74c.png)
![2022-04-20_03 36 42](https://user-images.githubusercontent.com/2096384/164417097-4b21602c-ed40-40af-a8ae-582a76df5d45.png)

Cannot craft stone tools with Dacite or Schist:
![2022-04-21_01 29 48](https://user-images.githubusercontent.com/2096384/164417251-e91e2751-12fa-4926-9dbb-693f487c5fce.png)
![2022-04-21_01 29 54](https://user-images.githubusercontent.com/2096384/164417264-dd050384-b40c-48a6-91af-c78a00a5a7f0.png)

**Comment by lilypuree** [comment]
Except for the grassy regolith model, all is intended design.

**Comment by Reshy** [comment]
Plants growing on those surfaces is intended?  Alright, just wanted to know, does look somewhat janky.

The inability to craft stone tools with those stone types is a bit odd though as most of the other stones work correctly.
